create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text,
  created_at timestamptz not null default now()
);
